CREATE DATABASE T_Opflix;
USE T_Opflix;
CREATE TABLE PerfisUsuarios (
	IdPerfil INT PRIMARY KEY IDENTITY NOT NULL,
	Tipo VARCHAR(15) NOT NULL UNIQUE
);
CREATE TABLE Usuarios (
	IdUsuario INT PRIMARY KEY IDENTITY NOT NULL,
	Tipo INT FOREIGN KEY REFERENCES PerfisUsuarios(IdPerfil) NOT NULL,
	Nome TEXT NOT NULL,
	Email VARCHAR(255) UNIQUE NOT NULL,
	Senha VARCHAR(28) NOT NULL
);
--O HENRIQUE DO PASSADO NÃO RODOU NENHUM DESSES COMANDOS AINDA